services:

  terraform:
    image: hashicorp/terraform:1.12.2
    volumes:
      - '.:/app'
      - '~/.aws:/root/.aws:ro'
    working_dir: '/app'

  terraform-docs:
    image: cytopia/terraform-docs
    volumes:
      - '.:/app'
    working_dir: '/app'
